// Generated by scripts/ext-packages/generate-sdk-versions.mjs — do not edit by hand.
// Regenerate: pnpm ext-packages:gen
/**
 * Versions baked into generated projects. Derived at build time: extensionApi/uex
 * from the sibling packages' package.json, esbuild/typescript/nodeTypes from the
 * pnpm-workspace.yaml catalog. Guarded by a drift test.
 */
export interface SdkVersions {
  readonly extensionApi: string
  readonly uex: string
  readonly esbuild: string
  readonly typescript: string
  readonly nodeTypes: string
}

export const SDK_VERSIONS: SdkVersions = {
  extensionApi: '0.12.1',
  uex: '0.3.1',
  esbuild: '^0.25.0',
  typescript: '^5.8.0',
  nodeTypes: '^22.0.0',
}
