// Generated by scripts/ext-packages/generate-sdk-versions.mjs — do not edit by hand.
// Regenerate: pnpm ext-packages:gen
/**
 * Versions baked into generated projects. Derived at build time: extensionApi/uex/
 * e2eHarness/e2eContract from the sibling packages' package.json,
 * esbuild/typescript/nodeTypes/vitest/@playwright/test from the pnpm-workspace.yaml
 * catalog. Guarded by a drift test.
 */
export interface SdkVersions {
  readonly extensionApi: string
  readonly uex: string
  readonly esbuild: string
  readonly typescript: string
  readonly nodeTypes: string
  readonly vitest: string
  readonly playwright: string
  readonly e2eHarness: string
  readonly e2eContract: string
}

export const SDK_VERSIONS: SdkVersions = {
  extensionApi: '0.13.0',
  uex: '0.3.2',
  esbuild: '^0.25.0',
  typescript: '^5.8.0',
  nodeTypes: '^22.0.0',
  vitest: '^3.0.0',
  playwright: '^1.62.0',
  e2eHarness: '0.1.0',
  e2eContract: '0.1.0',
}
