/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *  Adapted from Microsoft VSCode for Universe Editor.
 *  Source: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/themes/browser/fileIconThemeData.ts
 *--------------------------------------------------------------------------------------------*/

/**
 * FileIconThemeData —— VSCode `FileIconThemeData` 的对等物（裁剪版）。
 *
 * 一个文件图标主题 = manifest 里 `contributes.iconThemes[]` 声明的元数据 +
 * 一份主题 JSON。加载（`ensureLoaded`）= 读 JSON → `processIconThemeDocument`
 * 生成整段 CSS（选择器驱动：`.show-file-icons .xxx-ext-file-icon.file-icon::before`
 * 等）→ 缓存在 `styleSheetContent`，由 WorkbenchThemeService 注入
 * `style.contributedFileIconTheme`。
 *
 * 渲染层的协议类名（`file-icon` / `<ext>-ext-file-icon` / `mi-<name>-name-file-icon`
 * …）由 `workbench/files/fileIconClasses.ts` 在渲染 FileIcon 时生成——CSS 与
 * DOM 两侧按同一套 VSCode 类名协议对齐（`getIconClasses.ts` 的对应物）。
 */

import { URI, type IFileIconTheme } from '@universe-editor/platform'
import { parse, printParseErrorCode, type ParseError } from 'jsonc-parser'
import { processIconThemeDocument, type IIconThemeDocument } from './generateFileIconThemeCss.js'

export interface IIconThemeContributionShape {
  readonly id: string
  readonly label?: string
  readonly path: string
}

export interface IIconThemeExtensionData {
  readonly extensionId: string
  readonly extensionIsBuiltin: boolean
}

export class FileIconThemeData implements IFileIconTheme {
  id: string
  label: string
  settingsId: string | null
  description?: string
  hasFileIcons = false
  hasFolderIcons = false
  hidesExplorerArrows = false
  isLoaded = false
  location?: URI
  extensionData?: IIconThemeExtensionData
  watch = false
  /** Generated by `processIconThemeDocument`; injected as `contributedFileIconTheme`. */
  styleSheetContent?: string
  /** Theme file (for the icon-theme file watcher). */
  loadedFiles: readonly URI[] = []

  private constructor(id: string, label: string, settingsId: string | null) {
    this.id = id
    this.label = label
    this.settingsId = settingsId
  }

  async ensureLoaded(
    readText: (uri: URI) => Promise<string>,
    resolveResourceUrl?: (resource: URI) => string,
  ): Promise<string | undefined> {
    return !this.isLoaded ? this.reload(readText, resolveResourceUrl) : this.styleSheetContent
  }

  async reload(
    readText: (uri: URI) => Promise<string>,
    resolveResourceUrl?: (resource: URI) => string,
  ): Promise<string | undefined> {
    const location = this.location
    if (location === undefined) {
      return this.styleSheetContent
    }
    const document_ = await loadIconThemeDocument(readText, location)
    this.loadedFiles = [location]
    const result = processIconThemeDocument(this.id, location, document_, resolveResourceUrl)
    this.styleSheetContent = result.content
    this.hasFileIcons = result.hasFileIcons
    this.hasFolderIcons = result.hasFolderIcons
    this.hidesExplorerArrows = result.hidesExplorerArrows
    this.isLoaded = true
    return this.styleSheetContent
  }

  static fromExtensionTheme(
    contribution: IIconThemeContributionShape,
    location: URI,
    extensionData: IIconThemeExtensionData,
  ): FileIconThemeData {
    // VSCode: id = `${extensionId}-${theme.id}` — unique across extensions.
    const id = `${extensionData.extensionId}-${contribution.id}`
    const theme = new FileIconThemeData(id, contribution.label ?? contribution.id, contribution.id)
    theme.location = location
    theme.extensionData = extensionData
    return theme
  }

  static createUnloadedTheme(id: string): FileIconThemeData {
    return new FileIconThemeData(id, '', `__${id}`)
  }

  static noIconTheme: FileIconThemeData = (() => {
    const theme = new FileIconThemeData('', 'None', null)
    theme.hasFileIcons = false
    theme.hasFolderIcons = false
    theme.hidesExplorerArrows = false
    theme.isLoaded = true
    theme.watch = false
    return theme
  })()

  toStorageSnapshot(): ISerializedFileIconThemeData {
    return {
      id: this.id,
      label: this.label,
      settingsId: this.settingsId,
      styleSheetContent: this.styleSheetContent ?? '',
      hasFileIcons: this.hasFileIcons,
      hasFolderIcons: this.hasFolderIcons,
      hidesExplorerArrows: this.hidesExplorerArrows,
    }
  }

  static fromStorageSnapshot(data: ISerializedFileIconThemeData): FileIconThemeData | undefined {
    if (!data || typeof data.id !== 'string') {
      return undefined
    }
    const theme = new FileIconThemeData(data.id, data.label ?? data.id, data.settingsId ?? null)
    theme.styleSheetContent = data.styleSheetContent
    theme.hasFileIcons = data.hasFileIcons === true
    theme.hasFolderIcons = data.hasFolderIcons === true
    theme.hidesExplorerArrows = data.hidesExplorerArrows === true
    theme.isLoaded = true
    return theme
  }
}

export interface ISerializedFileIconThemeData {
  id: string
  label?: string
  settingsId: string | null
  styleSheetContent: string
  hasFileIcons: boolean
  hasFolderIcons: boolean
  hidesExplorerArrows: boolean
}

/** Read + parse an icon theme JSON document (JSONC tolerated, comments allowed). */
export async function loadIconThemeDocument(
  readText: (uri: URI) => Promise<string>,
  location: URI,
): Promise<IIconThemeDocument> {
  const content = await readText(location)
  const errors: ParseError[] = []
  const value = parse(content, errors, { allowTrailingComma: true, disallowComments: false })
  if (errors.length > 0) {
    throw new Error(
      `Problems parsing file icon theme file: ${errors
        .map((e) => printParseErrorCode(e.error))
        .join(', ')}`,
    )
  }
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('Invalid format for file icon theme file: Object expected.')
  }
  return value as IIconThemeDocument
}
