// Generated by scripts/ext-packages/generate-sdk-versions.mjs — do not edit by hand.
// Regenerate: pnpm ext-packages:gen
/**
 * The extension API version uex itself was built against — used by the
 * engines.universe coverage warning (authors most often target the current
 * API). Derived at build time from packages/extension-api/package.json.
 */
export const CURRENT_API_VERSION = '0.12.1'
